import pandas as pd
import numpy as np
import sys

samples = pd.read_csv(os.path.abspath(
    config["sample_sheet"])).set_index("sample_name", drop=False)

# print(samples)

# Check fastq2, if all empty then dataset is single end
samples.loc[:, "seq_type"] = np.where(samples.fastq2.isna(), "se", "pe")

# if samples['fastq2'].isna().all():
#     sys.stderr.write("No paths found in 'fastq2' column of sample table - assuming samples are single end\n")
#     single_end = True
# else:
#     single_end = False

# Double check 
bool_flags = ["use_precomputed_bed", "use_custom_polya_bed", "use_precomputed_salmon_index", "run_differential_apa"]

for flag in bool_flags:
    assert isinstance(config[flag], bool), f"{flag} must be True/False boolean, {config[flag]} (type {type(config[flag])}) was provided"

#assert isinstance(config["run_differential_apa"], bool), f"'run_differential' must be True/False boolean, {config['run_differential']} (type {type(config['run_differential'])}) was provided"



include: "rules/preprocess_annotation.smk"
include: "rules/qapa_build.smk"
include: "rules/qapa_fasta.smk"
include: "rules/salmon.smk"
include: "rules/qapa_quant.smk"
include: "rules/differential_apa.smk"

#-------------------------------------------------------------------------------
localrules: finish

rule finish:
    """
    """
    input:
        expand(os.path.join(config["out_dir"], "salmon", "quant", "{seq_type}", "{sample}", "quant.sf"),
               zip,
               seq_type=samples.seq_type.tolist(),  sample=samples.index.tolist()),
        rules.qapa_quant_combined.output,
        rules.tximport.output.tx_counts,
        rules.tximport.output.gene_counts


#-------------------------------------------------------------------------------
# How did it go?
#-------------------------------------------------------------------------------
onsuccess:
    print("Workflow finished, no error")

onerror:
    print("An error occurred, check log at %s." % {log})
